[Unit]
Description=Postgres database
After=docker-tcp.socket
Requires=docker-tcp.socket

[Service]
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill database-01
ExecStartPre=-/usr/bin/docker rm database-01
ExecStartPre=/usr/bin/docker pull yorrick/database
ExecStart=/usr/bin/docker run --name database-01 -p 5432:5432 yorrick/database


[Unit]
Description=Announce database
BindsTo=database.service

[Service]
ExecStart=/bin/sh -c "while true; do etcdctl set /services/database '{ \"host\": \"%H\", \"port\": 5432, \"version\": \"52c7248a14\" }' --ttl 60; sleep 45; done"
ExecStop=/usr/bin/etcdctl rm /services/database

[X-Fleet]
MachineOf=database.service

