#!/bin/bash

# Fail hard and fast
set -eo pipefail

export ETCD_PORT=${ETCD_PORT:-4001}
# 172.17.42.1 is the IP of docker bridge
export HOST_IP=${HOST_IP:-172.17.42.1}
export ETCD=$HOST_IP:4001

echo "[uwsgi] booting container. ETCD: $ETCD"

# Loop until confd has updated the nginx config
until confd -onetime -node $ETCD -config-file /application/flask.toml; do
  echo "[uwsgi] waiting for confd to refresh config.py"
  sleep 5
done

# Run confd in the background to watch the upstream servers
confd -interval 10 -node $ETCD -config-file /application/flask.toml &
echo "[uwsgi] confd is listening for changes on etcd..."

# Start nginx
echo "[uwsgi] starting uwsgi service..."
uwsgi --http 0.0.0.0:8000 --master --module app --callable app --touch-reload /application/uwsgi_reload

# Tail all nginx log files
tail -f /var/log/application.log
