---

- name: Install cloud config file
  template: src=user-data.yml dest=/var/lib/coreos-vagrant/vagrantfile-user-data
  sudo: yes

- name: Wait for cloud config to be applied
  wait_for: port=4001 delay=10

# random is necessary for messages not to clash when we setup mutilple cores
- name: Generate a random message
  shell: "echo message-$RANDOM"
  register: message

- name: Test that etcd is running
  shell: etcdctl set /{{ message.stdout }} Hello && etcdctl rm /{{ message.stdout }}

- name: Test that fleet is running
  command: fleetctl list-machines
  register: fleet_machines
